apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: EKS-cluster
  region: us-east-1 
  version: "1.32"

managedNodeGroups:
  - name: single-node-group
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 2
    volumeSize: 20
    ssh:
      allow: false