---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backup-rerun-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-creator-role
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-creator-binding
subjects:
- kind: ServiceAccount
  name: backup-rerun-sa
roleRef:
  kind: Role
  name: job-creator-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backup-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backup-webhook
  template:
    metadata:
      labels:
        app: backup-webhook
    spec:
      serviceAccountName: backup-rerun-sa
      containers:
      - name: webhook
        # Replace with your ECR image URI
        image: "hmasane757/python-webhook-mongo:V1"
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: backup-webhook-service
spec:
  selector:
    app: backup-webhook
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001